### ISSUE TITLE
Unable to open Dhewm3 on KDE Plasma

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.dhewm3.Dhewm3#1]
Hi

I use Arch + KDE Plasma.

Every time I try to open Dhewm3 I see this error message:

![dhewm3](https://user-images.githubusercontent.com/15967631/130103475-45112f0a-85a2-4db7-bfc3-a999fc38108f.png)

**Comment by Eonfge** [comment]
Same as with ezQuake;

https://github.com/flathub/io.github.ezQuake/issues/12#issuecomment-910517119

Hope you can get this working
