### ISSUE TITLE
Please remove usages of branch property from manifests

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.dhewm3.Dhewm3#25]
https://github.com/flathub/org.dhewm3.Dhewm3/blob/1f6a03555ec4a819698ee4870d9109b8027b5703/org.dhewm3.Dhewm3.yaml#L64

should be tag or commit or tag+commit

**Comment by Eonfge** [comment]
Does this really matter that much? It works either way and it's not the most critical of components.

**Comment by bbhtt** [comment]
Yes it is blocked via the linter.

**Comment by Eonfge** [comment]
I'll fix it when the next patch round is released. We just had one, two days ago so it can take some time:

https://github.com/flathub/org.dhewm3.Dhewm3/pull/24
