### ISSUE TITLE
Can't type into text boxes with wayland

### ISSUE THREAD

**Issue by pizzadude** [flathub/org.dhewm3.Dhewm3#8]
Hi, thanks for updating this flatpak. I noticed with KDE Wayland, I can't type into text boxes such as naming a save file. Gameplay controls work though. It works if I force Xwayland.

**Comment by pizzadude** [comment]
https://github.com/dhewm/dhewm3/issues/464

**Comment by Eonfge** [comment]
Mmh. Guess we'll have to roll-back Wayland support in that case.

**Comment by Eonfge** [comment]
Issue triaged for now: Wayland support has been reverted.

I'll pin it so that people know the limits of Wayland for the time being

**Comment by Eonfge** [comment]
Should all work now with SDL 2.24
